import { FormEvent, useEffect, useState } from 'react'
import { InstitutionSettings } from './institution'
import { getCurrentEmail, getRole } from './auth'
import { Availability, ScheduleInput, ScheduleProposal, TeachingRequest, generateLocalSchedule, scheduleIssues, validateScheduleInput } from './scheduling'
import { CoordinationArea } from './school'
import { useSchool } from './school-ui'
import { OperationEditor, OperationFeedback, PersonOptions, personName } from './operation-ui'
import { SchoolSave, SchoolTable } from './SchoolStudentFile'
import { downloadCsv } from './operations'
import './school-workspace.css'

const days = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes']
export default function Coordination({ settings }: { settings: InstitutionSettings }) {
  const store = useSchool(settings)
  const { data, teachers } = store
  const institutional = getRole() === 'institution'
  const email = getCurrentEmail()
  const [view, setView] = useState('Oferta del semestre')
  const [period, setPeriod] = useState(settings.grading.currentPeriod)
  const [request, setRequest] = useState<TeachingRequest | null>(null)
  const [availability, setAvailability] = useState<Availability | null>(null)
  const [area, setArea] = useState<CoordinationArea | null>(null)
  const [limitTeacher, setLimitTeacher] = useState('')
  const [maxHours, setMaxHours] = useState(20)
  const [proposal, setProposal] = useState<ScheduleProposal | null>(null)
  const [proposalInput, setProposalInput] = useState<ScheduleInput | null>(null)
  const [source, setSource] = useState('')
  const [busy, setBusy] = useState(false)
  const [ai, setAi] = useState<{ configured: boolean; token: string }>({ configured: false, token: '' })
  const [aiMessage, setAiMessage] = useState('Comprobando servicio de IA…')
  useEffect(() => { let live = true; fetch('/api/horarios/status').then(async (response) => { if (!response.ok) throw new Error(); return response.json() }).then((result) => { if (live) { setAi({ configured: result.configured === true, token: typeof result.token === 'string' ? result.token : '' }); setAiMessage(result.configured ? 'Servicio OpenAI conectado al backend.' : 'Configura OPENAI_API_KEY en el backend para activar la IA.') } }).catch(() => { if (live) setAiMessage('Inicia el backend de horarios para conectar OpenAI. El generador local está disponible.') }); return () => { live = false } }, [])
  const assignedPrograms = new Set(data.areas.filter((item) => item.email.toLowerCase() === email?.toLowerCase()).flatMap((item) => item.programIds))
  const groups = data.groups.filter((item) => item.period === period && (institutional || assignedPrograms.has(item.programId)))
  const requests = data.requests.filter((item) => groups.some((group) => group.id === item.groupId))
  const teacherIds = new Set(requests.map((item) => item.teacherId))
  const availableTeachers = teachers.filter((item) => institutional || teacherIds.has(item.id))
  const plan = settings.academicOffer.programs.find((item) => item.id === data.groups.find((group) => group.id === request?.groupId)?.programId)
  const allowedSubjects = new Set(plan?.curriculum.filter((term) => term.semester === data.groups.find((group) => group.id === request?.groupId)?.semester).flatMap((term) => term.subjects.map((subject) => subject.id)) ?? [])
  const currentInput: ScheduleInput = { requests, availability: data.availability.filter((item) => teacherIds.has(item.teacherId)), limits: data.limits.filter((item) => teacherIds.has(item.teacherId)) }
  function saveRequest(event: FormEvent) {
    event.preventDefault(); if (!request) return
    if (!groups.some((group) => group.id === request.groupId) || !allowedSubjects.has(request.subjectId) || !teachers.some((teacher) => teacher.id === request.teacherId)) { store.setError('La clase debe usar un grupo de tu área, una materia de su plan y un docente registrado.'); return }
    if (store.commit({ ...data, requests: data.requests.some((item) => item.id === request.id) ? data.requests.map((item) => item.id === request.id ? request : item) : [...data.requests, request] })) { setRequest(null); setProposal(null) }
  }
  function saveAvailability(event: FormEvent) {
    event.preventDefault(); if (!availability) return
    if (!availableTeachers.some((item) => item.id === availability.teacherId)) { store.setError('Selecciona un docente de las clases de tu área.'); return }
    const repeated = data.availability.some((item) => item.id !== availability.id && item.teacherId === availability.teacherId && item.day === availability.day && item.start === availability.start && item.end === availability.end)
    if (repeated) { store.setError('Ese tramo de disponibilidad ya está registrado.'); return }
    if (store.commit({ ...data, availability: data.availability.some((item) => item.id === availability.id) ? data.availability.map((item) => item.id === availability.id ? availability : item) : [...data.availability, availability] })) { setAvailability(null); setProposal(null) }
  }
  async function generate(withAi: boolean) {
    store.setError(''); setBusy(true); setProposal(null)
    const input: ScheduleInput = { requests, availability: data.availability.filter((item) => teacherIds.has(item.teacherId)), limits: data.limits.filter((item) => teacherIds.has(item.teacherId)) }
    try {
      if (!institutional) throw new Error('La generación global requiere al administrador del instituto para considerar todas las áreas.')
      if (!validateScheduleInput(input)) throw new Error('Registra clases y disponibilidades válidas antes de generar.')
      const result = withAi ? await (async () => { const response = await fetch('/api/horarios/generar', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CampusOne-Token': ai.token }, body: JSON.stringify(input), signal: AbortSignal.timeout(65000) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? 'El servicio no pudo generar el horario.'); return body as ScheduleProposal })() : generateLocalSchedule(input)
      const issues = scheduleIssues(input, result)
      if (issues.length) throw new Error(`Propuesta rechazada: ${issues.join(' ')}`)
      setProposal(result); setProposalInput(structuredClone(input)); setSource(withAi ? 'OpenAI' : 'Generador local')
    } catch (failure) { store.setError(failure instanceof Error ? failure.message : 'No se pudo generar la propuesta.') }
    finally { setBusy(false) }
  }
  const persisted = data.schedules.filter((item) => item.period === period).at(-1)
  const displayedSlots = proposal?.slots ?? persisted?.slots ?? []
  const displayedRequests = proposal ? proposalInput?.requests ?? [] : persisted?.requestSnapshot ?? []
  const scheduleRows = displayedSlots.filter((slot) => institutional || groups.some((group) => group.id === displayedRequests.find((item) => item.id === slot.requestId)?.groupId)).sort((a, b) => a.day - b.day || a.hour - b.hour).map((slot) => { const item = displayedRequests.find((request) => request.id === slot.requestId)!; return [days[slot.day], `${slot.hour}:00–${slot.hour + 1}:00`, data.groups.find((group) => group.id === item.groupId)?.code ?? item.groupId, data.subjects.find((subject) => subject.id === item.subjectId)?.name ?? item.subjectId, personName(teachers, item.teacherId), item.room] })
  return <section className="school-workspace"><div className="module-heading"><div><p className="date-label">COORDINACIÓN POR ÁREA</p><h1>Oferta semestral y horarios</h1><p>Define clases, responsables, disponibilidad y carga antes de generar una propuesta.</p></div></div><div className="operation-toolbar"><label>Periodo<input aria-label="Periodo de coordinación" disabled={busy} value={period} onChange={(event) => { setPeriod(event.target.value); setProposal(null); store.setError('') }} /></label></div><nav className="school-tabs" aria-label="Secciones de coordinación">{['Oferta del semestre', 'Disponibilidad y carga', 'Horarios', ...(institutional ? ['Áreas y encargados'] : [])].map((item) => <button key={item} className={view === item ? 'active' : ''} onClick={() => { setView(item); store.setError('') }}>{item}</button>)}</nav><OperationFeedback error={request || availability || area ? '' : store.error} notice={store.notice} />
    {!institutional && !assignedPrograms.size && <p className="directory-error">El instituto debe asignarte un área y sus carreras antes de preparar la oferta.</p>}
    {view === 'Oferta del semestre' && <><button className="primary-button compact" disabled={store.blocked || !groups.length} onClick={() => { store.setError(''); setRequest({ id: crypto.randomUUID(), groupId: '', subjectId: '', teacherId: '', room: '', hours: 4 }) }}>Asignar materia a grupo</button><div className="directory-table-wrap"><table><thead><tr><th>Grupo</th><th>Materia</th><th>Docente</th><th>Horas semanales</th><th>Aula</th><th>Acciones</th></tr></thead><tbody>{requests.map((item) => <tr key={item.id}><td>{groups.find((group) => group.id === item.groupId)?.code}</td><td>{data.subjects.find((subject) => subject.id === item.subjectId)?.name}</td><td>{personName(teachers, item.teacherId)}</td><td>{item.hours}</td><td>{item.room}</td><td><button className="secondary-button" onClick={() => { setRequest({ ...item }); store.setError('') }}>Editar clase</button></td></tr>)}</tbody></table></div>{!groups.length && <p>Primero crea grupos de este periodo en Control escolar.</p>}</>}
    {view === 'Disponibilidad y carga' && <><button className="primary-button compact" disabled={store.blocked || !availableTeachers.length} onClick={() => { store.setError(''); setAvailability({ id: crypto.randomUUID(), teacherId: '', day: 0, start: 8, end: 14 }) }}>Registrar disponibilidad</button><div className="directory-table-wrap"><table><thead><tr><th>Docente</th><th>Día</th><th>Disponible desde</th><th>Hasta</th><th>Acción</th></tr></thead><tbody>{data.availability.filter((item) => institutional || teacherIds.has(item.teacherId)).map((item) => <tr key={item.id}><td>{personName(teachers, item.teacherId)}</td><td>{days[item.day]}</td><td>{item.start}:00</td><td>{item.end}:00</td><td><button className="secondary-button" onClick={() => { setAvailability({ ...item }); store.setError('') }}>Editar disponibilidad</button></td></tr>)}</tbody></table></div><h2>Carga por docente en el periodo</h2><SchoolTable headers={['Docente', 'Horas asignadas', 'Máximo semanal']} rows={availableTeachers.map((teacher) => [teacher.name, data.requests.filter((item) => item.teacherId === teacher.id && data.groups.some((group) => group.id === item.groupId && group.period === period)).reduce((sum, item) => sum + item.hours, 0), data.limits.find((item) => item.teacherId === teacher.id)?.maxHours ?? 20])} /><form className="directory-form" onSubmit={(event) => { event.preventDefault(); if (!availableTeachers.some((item) => item.id === limitTeacher)) return; if (store.commit({ ...data, limits: [...data.limits.filter((item) => item.teacherId !== limitTeacher), { teacherId: limitTeacher, maxHours }] })) setProposal(null) }}><label>Docente<select required aria-label="Docente para carga máxima" value={limitTeacher} onChange={(event) => setLimitTeacher(event.target.value)}><PersonOptions records={availableTeachers} /></select></label><label>Máximo de horas semanales<input required type="number" min={1} max={60} value={maxHours} onChange={(event) => setMaxHours(Number(event.target.value))} /></label><SchoolSave error={store.error} blocked={store.blocked} /></form></>}
    {view === 'Áreas y encargados' && institutional && <><button className="primary-button compact" disabled={store.blocked} onClick={() => { store.setError(''); setArea({ id: crypto.randomUUID(), name: '', email: '', programIds: [] }) }}>Registrar área</button><div className="directory-table-wrap"><table><thead><tr><th>Área</th><th>Coordinador</th><th>Carreras</th><th>Acción</th></tr></thead><tbody>{data.areas.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.email}</td><td>{item.programIds.map((id) => settings.academicOffer.programs.find((program) => program.id === id)?.name ?? id).join(', ')}</td><td><button className="secondary-button" onClick={() => setArea(structuredClone(item))}>Editar área</button></td></tr>)}</tbody></table></div><p>El usuario necesita el permiso Coordinación académica. Solo verá los grupos de las carreras asignadas a su correo.</p></>}
    {view === 'Horarios' && <><p>{aiMessage}</p><p>La generación global corresponde al instituto y contempla todas las áreas del periodo. Ninguna propuesta se guarda automáticamente. Las sesiones son bloques de una hora, de lunes a viernes, entre 7:00 y 22:00.</p><div className="operation-card-actions"><button className="primary-button compact" disabled={store.blocked || busy || !institutional || !ai.configured} onClick={() => generate(true)}>{busy ? 'Generando…' : 'Generar con OpenAI'}</button><button className="secondary-button" disabled={store.blocked || busy || !institutional} onClick={() => generate(false)}>Generar propuesta local</button>{proposal && <button className="secondary-button" disabled={busy || store.blocked} onClick={() => { if (!proposalInput) return; if (JSON.stringify(currentInput) !== JSON.stringify(proposalInput)) { store.setError('La oferta cambió. Genera una propuesta nueva antes de guardar.'); return } const issues = scheduleIssues(currentInput, proposal); if (issues.length) { store.setError(issues.join(' ')); return } if (store.commit({ ...data, schedules: [...data.schedules, { id: crypto.randomUUID(), period, slots: proposal.slots, source, createdAt: new Date().toISOString(), requestSnapshot: proposalInput.requests }] })) setProposal(null) }}>Guardar propuesta revisada</button>}<button className="secondary-button" disabled={!scheduleRows.length} onClick={() => downloadCsv(`Horario-${period}`, ['Día', 'Hora', 'Grupo', 'Materia', 'Docente', 'Aula'], scheduleRows)}>Exportar horario CSV</button></div><p>{proposal ? `Propuesta sin guardar · ${source}` : persisted ? `Última propuesta guardada · ${persisted.source} · ${persisted.createdAt.slice(0, 10)}` : 'Sin propuesta generada.'}</p><SchoolTable headers={['Día', 'Hora', 'Grupo', 'Materia', 'Docente', 'Aula']} rows={scheduleRows} /></>}
    {request && <OperationEditor title="Clase del semestre" close={() => setRequest(null)}><form className="directory-form" onSubmit={saveRequest}><label>Grupo<select required aria-label="Grupo de la clase" value={request.groupId} onChange={(event) => setRequest({ ...request, groupId: event.target.value, subjectId: '' })}><option value="">Seleccionar</option>{groups.map((item) => <option key={item.id} value={item.id}>{item.code} · semestre {item.semester}</option>)}</select></label><label>Materia del plan<select required aria-label="Materia de la clase" value={request.subjectId} onChange={(event) => { const subject = data.subjects.find((item) => item.id === event.target.value); setRequest({ ...request, subjectId: event.target.value, hours: subject?.hours ?? 4 }) }}><option value="">Seleccionar</option>{data.subjects.filter((item) => allowedSubjects.has(item.id)).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Docente<select required aria-label="Docente de la clase" value={request.teacherId} onChange={(event) => setRequest({ ...request, teacherId: event.target.value })}><PersonOptions records={teachers} selectedId={request.teacherId} /></select></label><label>Aula<input required value={request.room} onChange={(event) => setRequest({ ...request, room: event.target.value })} /></label><label>Horas semanales<input required type="number" min={1} max={12} value={request.hours} onChange={(event) => setRequest({ ...request, hours: Number(event.target.value) })} /></label><SchoolSave error={store.error} blocked={store.blocked} /></form></OperationEditor>}
    {availability && <OperationEditor title="Disponibilidad del docente" close={() => setAvailability(null)}><form className="directory-form" onSubmit={saveAvailability}><label>Docente<select required aria-label="Docente disponible" value={availability.teacherId} onChange={(event) => setAvailability({ ...availability, teacherId: event.target.value })}><PersonOptions records={availableTeachers} selectedId={availability.teacherId} /></select></label><label>Día<select aria-label="Día disponible" value={availability.day} onChange={(event) => setAvailability({ ...availability, day: Number(event.target.value) })}>{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></label><label>Desde (hora)<input required type="number" min={7} max={21} value={availability.start} onChange={(event) => setAvailability({ ...availability, start: Number(event.target.value) })} /></label><label>Hasta (hora)<input required type="number" min={8} max={22} value={availability.end} onChange={(event) => setAvailability({ ...availability, end: Number(event.target.value) })} /></label><SchoolSave error={store.error} blocked={store.blocked} /></form></OperationEditor>}
    {area && institutional && <OperationEditor title="Área y coordinación" close={() => setArea(null)}><form className="directory-form" onSubmit={(event) => { event.preventDefault(); if (!settings.accessControl.users.some((user) => user.email === area.email && user.status === 'Activo')) { store.setError('Selecciona un usuario activo del sistema.'); return } if (store.commit({ ...data, areas: data.areas.some((item) => item.id === area.id) ? data.areas.map((item) => item.id === area.id ? area : item) : [...data.areas, area] })) setArea(null) }}><label>Nombre del área<input required value={area.name} onChange={(event) => setArea({ ...area, name: event.target.value })} /></label><label>Coordinador<select required aria-label="Coordinador del área" value={area.email} onChange={(event) => setArea({ ...area, email: event.target.value })}><option value="">Seleccionar</option>{settings.accessControl.users.filter((item) => item.status === 'Activo').map((item) => <option key={item.id} value={item.email}>{item.name} · {item.email}</option>)}</select></label><fieldset className="operation-checklist directory-wide"><legend>Carreras a cargo</legend>{settings.academicOffer.programs.map((item) => <label key={item.id}><input type="checkbox" checked={area.programIds.includes(item.id)} onChange={(event) => setArea({ ...area, programIds: event.target.checked ? [...area.programIds, item.id] : area.programIds.filter((id) => id !== item.id) })} />{item.name}</label>)}</fieldset><SchoolSave error={store.error} blocked={store.blocked} /></form></OperationEditor>}
  </section>
}
