import { FormEvent, useState } from 'react'
import { InstitutionSettings } from './institution'
import { getCurrentEmail } from './auth'
import { Grade, Movement, StudentBlock, applyMovement, blockingReasons, studentIsWithdrawn, studentProgram } from './school'
import { SchoolStore } from './school-ui'
import { printSchoolDocument } from './school-print'
import { OperationEditor, OperationFeedback } from './operation-ui'
import DocumentFiles from './DocumentFiles'

export default function SchoolStudentFile({ store, settings, selectedId, select, initialTab = 'Resumen' }: { store: SchoolStore; settings: InstitutionSettings; selectedId: string; select: (id: string) => void; initialTab?: string }) {
  const [query, setQuery] = useState('')
  const [tab, setTab] = useState(initialTab)
  const [block, setBlock] = useState<StudentBlock | null>(null)
  const [grade, setGrade] = useState<Grade | null>(null)
  const [movement, setMovement] = useState<Movement | null>(null)
  const [release, setRelease] = useState<{ id: string; reason: string } | null>(null)
  const { data, students } = store
  const student = students.find((item) => item.id === selectedId)
  const programId = student ? studentProgram(data, student.id, student.area, settings) : ''
  const program = settings.academicOffer.programs.find((item) => item.id === programId)
  const grades = data.grades.filter((item) => item.studentId === selectedId)
  const rows = grades.map((item) => { const subject = data.subjects.find((entry) => entry.id === item.subjectId); return [item.period, subject?.code ?? '', subject?.name ?? 'Materia no disponible', subject?.credits ?? 0, item.grade, item.grade >= settings.grading.passingGrade ? 'Aprobada' : 'No aprobada', item.origin, item.reference] })
  function print(kind: string) {
    if (!student) return
    const reasons = blockingReasons(data, student.id, 'Documentos')
    if (reasons.length) { store.setError(`Emisión bloqueada: ${reasons.join('; ')}`); return }
    if (kind === 'Constancia de estudios' && (studentIsWithdrawn(data, student.id) || student.status !== 'Activo')) { store.setError('La constancia de estudios requiere un alumno activo.'); return }
    const table = kind === 'Kárdex' ? { headers: ['Periodo', 'Clave', 'Materia', 'Créditos', 'Calificación', 'Resultado', 'Origen', 'Referencia'], rows } : { headers: ['Dato', 'Valor'], rows: [['Matrícula', student.number], ['Alumno', student.name], ['Carrera', program?.name ?? 'Sin carrera vinculada'], ['Plan', program?.planVersion ?? 'Sin plan'], ['Periodo', settings.grading.currentPeriod], ['Estado', studentIsWithdrawn(data, student.id) ? 'Baja' : student.status]] }
    printSchoolDocument(kind, settings.name, `${student.number} · ${student.name}`, table.headers, table.rows)
  }
  function saveBlock(event: FormEvent) { event.preventDefault(); if (block && store.commit({ ...data, blocks: [...data.blocks, block] })) setBlock(null) }
  function saveGrade(event: FormEvent) { event.preventDefault(); if (!grade) return; const next = data.grades.some((item) => item.id === grade.id) ? data.grades.map((item) => item.id === grade.id ? grade : item) : [...data.grades, grade]; if (store.commit({ ...data, grades: next })) setGrade(null) }
  function saveMovement(event: FormEvent) {
    event.preventDefault(); if (!movement || !student) return
    if (movement.type !== 'Justificante' && movement.date > new Date().toLocaleDateString('en-CA')) { store.setError('Este movimiento se aplica al guardar. Usa una fecha actual o pasada.'); return }
    if (movement.type === 'Cambio de carrera' && (movement.programId === programId || !settings.academicOffer.programs.some((item) => item.id === movement.programId))) { store.setError('Selecciona una carrera de destino distinta a la actual.'); return }
    if (movement.type === 'Reingreso' && !studentIsWithdrawn(data, student.id)) { store.setError('El alumno no tiene una baja registrada en Control escolar.'); return }
    if (store.commit(applyMovement(data, movement))) setMovement(null)
  }
  return <section><div className="operation-toolbar"><label>Buscar alumno<input aria-label="Buscar alumno en Control escolar" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nombre o matrícula" /></label><select aria-label="Seleccionar expediente" value={selectedId} onChange={(event) => { select(event.target.value); setTab(initialTab); store.setError('') }}><option value="">Seleccionar alumno</option>{students.filter((item) => `${item.name} ${item.number}`.toLowerCase().includes(query.toLowerCase()) || item.id === selectedId).map((item) => <option key={item.id} value={item.id}>{item.number} · {item.name}</option>)}</select></div>
    {!student ? <p className="operation-panel">Selecciona un alumno para consultar su expediente académico.</p> : <>
      <article className="operation-panel"><div className="operation-panel-heading"><div><h2>{student.name}</h2><p>{student.number} · {program?.name ?? 'Sin carrera vinculada'} · {studentIsWithdrawn(data, student.id) ? 'Baja registrada' : student.status}</p></div><div className="operation-card-actions"><button className="secondary-button" onClick={() => print('Kárdex')}>Imprimir kárdex</button><button className="secondary-button" onClick={() => print('Constancia de estudios')}>Imprimir constancia</button><button className="secondary-button" onClick={() => print('Ficha de expediente')}>Imprimir expediente</button></div></div><nav className="school-tabs" aria-label="Secciones del expediente">{['Resumen', 'Kárdex', 'Bloqueos', 'Movimientos', 'Documentos'].map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => { setTab(item); store.setError('') }}>{item}</button>)}</nav><OperationFeedback error={store.error} notice={store.notice} />
        {tab === 'Resumen' && <><dl className="directory-details"><div><dt>Correo</dt><dd>{student.email}</dd></div><div><dt>Teléfono</dt><dd>{student.phone || 'Sin registrar'}</dd></div><div><dt>Plan vigente</dt><dd>{program?.planVersion ?? 'Sin vincular'}</dd></div><div><dt>Semestre</dt><dd>{student.semester}</dd></div></dl><label>Carrera y plan del expediente<select aria-label="Carrera del expediente" value={programId} onChange={(event) => { const next = { ...data, careers: [...data.careers.filter((item) => item.studentId !== student.id), { studentId: student.id, programId: event.target.value }] }; if (programId && programId !== event.target.value) { store.setError('Para cambiar una carrera ya vinculada, registra un Cambio de carrera en Movimientos.'); return } store.commit(next) }}><option value="">Seleccionar carrera</option>{settings.academicOffer.programs.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.planVersion}</option>)}</select></label><h3>Grupos inscritos</h3><SchoolTable headers={['Grupo', 'Periodo', 'Semestre']} rows={data.groups.filter((item) => item.studentIds.includes(student.id)).map((item) => [item.code, item.period, item.semester])} /></>}
        {tab === 'Kárdex' && <><p>Promedio simple: {grades.length ? (grades.reduce((sum, item) => sum + item.grade, 0) / grades.length).toFixed(2) : 'Sin evaluaciones'}. El historial conserva los periodos y referencias de revalidación.</p><button className="secondary-button" disabled={store.blocked} onClick={() => { store.setError(''); setGrade({ id: crypto.randomUUID(), studentId: student.id, subjectId: '', period: settings.grading.currentPeriod, grade: 0, origin: 'Curso', reference: '' }) }}>Registrar calificación o revalidación</button><div className="directory-table-wrap"><table><thead><tr>{['Periodo', 'Materia', 'Calificación', 'Origen', 'Referencia', 'Acción'].map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{grades.map((item) => <tr key={item.id}><td>{item.period}</td><td>{data.subjects.find((subject) => subject.id === item.subjectId)?.name}</td><td>{item.grade}</td><td>{item.origin}</td><td>{item.reference || '—'}</td><td><button className="secondary-button" onClick={() => setGrade({ ...item })}>Editar calificación</button></td></tr>)}</tbody></table></div></>}
        {tab === 'Bloqueos' && <><button className="secondary-button" disabled={store.blocked} onClick={() => { store.setError(''); setBlock({ id: crypto.randomUUID(), studentId: student.id, area: 'Documentos', reason: '', scope: 'Inscripción', active: true, createdAt: new Date().toISOString(), releasedAt: '', releaseReason: '' }) }}>Asignar bloqueo</button><div className="directory-table-wrap"><table><thead><tr><th>Área</th><th>Motivo</th><th>Alcance</th><th>Estado</th><th>Liberación</th></tr></thead><tbody>{data.blocks.filter((item) => item.studentId === student.id).map((item) => <tr key={item.id}><td>{item.area}</td><td>{item.reason}</td><td>{item.scope}</td><td>{item.active ? 'Activo' : 'Liberado'}</td><td>{item.active ? <button className="secondary-button" onClick={() => setRelease({ id: item.id, reason: '' })}>Liberar bloqueo</button> : `${item.releaseReason} · ${item.releasedAt.slice(0, 10)}`}</td></tr>)}</tbody></table></div></>}
        {tab === 'Movimientos' && <><p>Bajas y cambios de carrera retiran al alumno de sus grupos actuales, sin borrar el kárdex. Los justificantes no eliminan asistencias automáticamente.</p><button className="secondary-button" disabled={store.blocked} onClick={() => { store.setError(''); setMovement({ id: crypto.randomUUID(), studentId: student.id, type: 'Baja temporal', reason: '', date: '', end: '', programId: '', author: getCurrentEmail() ?? 'Personal de Control escolar' }) }}>Registrar movimiento</button><SchoolTable headers={['Fecha', 'Movimiento', 'Motivo', 'Destino / hasta', 'Registrado por']} rows={data.movements.filter((item) => item.studentId === student.id).map((item) => [item.date, item.type, item.reason, item.type === 'Cambio de carrera' ? settings.academicOffer.programs.find((program) => program.id === item.programId)?.name ?? item.programId : item.end, item.author])} /></>}
      </article>
      {tab === 'Documentos' && <DocumentFiles key={student.id} ownerType="student" ownerId={student.id} />}
    </>}
    {block && <OperationEditor title="Bloqueo del alumno" close={() => setBlock(null)}><form className="directory-form" onSubmit={saveBlock}><label>Área<select aria-label="Área del bloqueo" value={block.area} onChange={(event) => setBlock({ ...block, area: event.target.value })}>{['Documentos', 'Biblioteca', 'Finanzas', 'Control escolar', 'Otra'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Alcance<select aria-label="Alcance del bloqueo" value={block.scope} onChange={(event) => setBlock({ ...block, scope: event.target.value as StudentBlock['scope'] })}><option>Inscripción</option><option>Documentos</option><option>Ambos</option></select></label><label className="directory-wide">Motivo<textarea required value={block.reason} onChange={(event) => setBlock({ ...block, reason: event.target.value })} /></label><SchoolSave error={store.error} blocked={store.blocked} /></form></OperationEditor>}
    {release && <OperationEditor title="Liberar bloqueo" close={() => setRelease(null)}><form className="directory-form" onSubmit={(event) => { event.preventDefault(); if (!release.reason.trim()) return; if (store.commit({ ...data, blocks: data.blocks.map((item) => item.id === release.id ? { ...item, active: false, releaseReason: release.reason.trim(), releasedAt: new Date().toISOString() } : item) })) setRelease(null) }}><label className="directory-wide">Motivo de liberación<textarea required value={release.reason} onChange={(event) => setRelease({ ...release, reason: event.target.value })} /></label><SchoolSave error={store.error} blocked={store.blocked} /></form></OperationEditor>}
    {grade && <OperationEditor title="Calificación y revalidación" close={() => setGrade(null)}><form className="directory-form" onSubmit={saveGrade}><label>Materia<select required aria-label="Materia del kárdex" value={grade.subjectId} onChange={(event) => setGrade({ ...grade, subjectId: event.target.value })}><option value="">Seleccionar materia</option>{data.subjects.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Periodo<input required value={grade.period} onChange={(event) => setGrade({ ...grade, period: event.target.value })} /></label><label>Calificación<input required type="number" min={0} max={100} step="0.1" value={grade.grade} onChange={(event) => setGrade({ ...grade, grade: Number(event.target.value) })} /></label><label>Origen<select aria-label="Origen de calificación" value={grade.origin} onChange={(event) => setGrade({ ...grade, origin: event.target.value as Grade['origin'] })}><option>Curso</option><option>Revalidación</option></select></label><label className="directory-wide">Referencia, institución y dictamen<input required={grade.origin === 'Revalidación'} value={grade.reference} onChange={(event) => setGrade({ ...grade, reference: event.target.value })} /></label><SchoolSave error={store.error} blocked={store.blocked} /></form></OperationEditor>}
    {movement && <OperationEditor title="Movimiento escolar" close={() => setMovement(null)}><form className="directory-form" onSubmit={saveMovement}><label>Tipo<select aria-label="Tipo de movimiento" value={movement.type} onChange={(event) => setMovement({ ...movement, type: event.target.value as Movement['type'] })}>{['Baja temporal', 'Baja definitiva', 'Reingreso', 'Cambio de carrera', 'Justificante'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Fecha efectiva<input required type="date" value={movement.date} onChange={(event) => setMovement({ ...movement, date: event.target.value })} /></label>{movement.type === 'Justificante' && <label>Hasta<input required type="date" min={movement.date} value={movement.end} onChange={(event) => setMovement({ ...movement, end: event.target.value })} /></label>}{movement.type === 'Cambio de carrera' && <label>Carrera de destino<select aria-label="Carrera de destino" required value={movement.programId} onChange={(event) => setMovement({ ...movement, programId: event.target.value })}><option value="">Seleccionar</option>{settings.academicOffer.programs.filter((item) => item.id !== programId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label className="directory-wide">Motivo y autorización<textarea required value={movement.reason} onChange={(event) => setMovement({ ...movement, reason: event.target.value })} /></label><SchoolSave error={store.error} blocked={store.blocked} /></form></OperationEditor>}
  </section>
}
export function SchoolTable({ headers, rows }: { headers: string[]; rows: (string | number)[][] }) { return <div className="directory-table-wrap"><table><thead><tr>{headers.map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((item, column) => <td key={column}>{item || '—'}</td>)}</tr>)}</tbody></table>{!rows.length && <p>Sin registros.</p>}</div> }
export function SchoolSave({ error, blocked }: { error: string; blocked: boolean }) { return <div className="directory-wide"><OperationFeedback error={error} notice="" /><button className="primary-button compact" disabled={blocked}>Guardar registro</button></div> }
